In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
OCORRENCIAS = r'C:\Users\eduarda.castilho\Documents\UC2_aulas\BASES\03.BaseDPEvolucaoMensalCisp.csv'
DP = r'C:\Users\eduarda.castilho\Documents\UC2_aulas\BASES\08.DP.csv'

df_ocorrencias = pd.read_csv(
    OCORRENCIAS,
    sep=';',
    encoding= 'iso-8859-1'
)

df_DP = pd.read_csv(
    DP

)

In [12]:
df_merge = df_ocorrencias.merge(
    df_DP,
    how='left',
    right_on='codDP',
    left_on= 'cisp'
)

df_roubo_transeunte= df_merge[[
    'cisp', 'nome', 'roubo_transeunte', 'ano', 'mes', 'regiao'
]]

df_roubo_transeunte.info()
df_roubo_transeunte['nome'].isna() #verifica erros 
df_roubo_transeunte['nome'].isnull() #verifica vazio

df_roubo_transeunte = df_roubo_transeunte.fillna('DP não informada.') #'completa' os erros

<class 'pandas.DataFrame'>
RangeIndex: 34848 entries, 0 to 34847
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cisp              34848 non-null  int64
 1   nome              34787 non-null  str
 2   roubo_transeunte  34848 non-null  int64
 3   ano               34848 non-null  int64
 4   mes               34848 non-null  int64
 5   regiao            34848 non-null  str
dtypes: int64(4), str(2)
memory usage: 1.6 MB

In [13]:
df_roubo_transeunte_agg = (
    df_roubo_transeunte.groupby('nome')['roubo_transeunte']
    .sum().reset_index().sort_values(by='roubo_transeunte', ascending=False)
)
df_roubo_transeunte_agg

                                nome  roubo_transeunte
51         059ª DP - Duque de Caxias             59518
56      064ª DP - São João de Meriti             43262
30                   034ª DP - Bangu             42713
64               074ª DP - Alcântara             35892
25               029ª DP - Madureira             31430
..                               ...               ...
117                142ª DP - Cambuci                13
129   156ª DP - Santa Maria Madalena                 7
76          092ª DP - Rio das Flores                 5
128  155ª DP - São Sebastião do Alto                 4
93               111ª DP - Sumidouro                 3

[138 rows x 2 columns]

In [26]:
roubo_transeunte_array = np.array(df_roubo_transeunte_agg['roubo_transeunte'])

media = np.mean(roubo_transeunte_array)
mediana = np.median(roubo_transeunte_array)
desvio = np.std(roubo_transeunte_array)
max = np.max(roubo_transeunte_array)
min = np.min(roubo_transeunte_array)
amplitude = (max - min)

delta_media_mediana = (media - mediana) # -> deslocamento

q1 = np.percentile(roubo_transeunte_array, 25)
q3 = np.percentile(roubo_transeunte_array, 75)
iqr = q3 - q1
#outliers - preparação
limite_inferior = q1 - 1.5*iqr
limite_superior = q3 + 1.5*iqr

desvio = np.std(roubo_transeunte_array)
cv = (desvio/media)*100

#formato de distribuição
assimetria = df_roubo_transeunte['roubo_transeunte'].skew()
curtose = df_roubo_transeunte['roubo_transeunte'].kurtosis()

In [29]:

print(f'Média: {media:.2f}')
print(f'Mediana: {mediana:.2f}')
print(f'Desvio padrão: {desvio:.2f}')
print(f'Q1: {q1:.2f}')
print(f'Q2/Mediana: {mediana:.2f}')
print(f'Q3: {q3:.2f}')
print(f'IQR: {iqr:.2f}')
print(f'Amplitude: {amplitude:.2f}')
print(f'Desvio padrão: {desvio:.2f}')
print(f'Coeficiente de Variação(CV): {cv:.2f}')
print(f'Delta Média-Mediana: {delta_media_mediana:.2f}')
print(f'Limite Inferior: {limite_inferior}')
print(f'Limite Superior: {limite_superior}')
print(f'Curtose: {curtose:.4f}')
print(f'Assimetria: {assimetria:.4f}')

Média: 8822.72
Mediana: 3799.50
Desvio padrão: 10972.33
Q1: 173.75
Q2/Mediana: 3799.50
Q3: 16100.50
IQR: 15926.75
Amplitude: 59515.00
Desvio padrão: 10972.33
Coeficiente de Variação(CV): 124.36
Delta Média-Mediana: 5023.22
Limite Inferior: -23716.375
Limite Superior: 39990.625
Curtose: 7.7882
Assimetria: 2.3693

In [9]:
df_merge = df_ocorrencias.merge(
    df_DP,
    how='left',
    right_on='codDP',
    left_on= 'cisp'
)

df_roubo_celular= df_merge[[
    'cisp', 'nome', 'roubo_celular', 'ano', 'mes', 'regiao'
]]

df_roubo_celular.info()
df_roubo_celular['nome'].isna() #verifica erros 
df_roubo_celular['nome'].isnull() #verifica vazio

df_roubo_celular = df_roubo_celular.fillna('DP não informada.') #'completa' os erros

<class 'pandas.DataFrame'>
RangeIndex: 34848 entries, 0 to 34847
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cisp           34848 non-null  int64
 1   nome           34787 non-null  str
 2   roubo_celular  34848 non-null  int64
 3   ano            34848 non-null  int64
 4   mes            34848 non-null  int64
 5   regiao         34848 non-null  str
dtypes: int64(4), str(2)
memory usage: 1.6 MB

In [17]:
df_roubo_celular_agg = (
    df_roubo_celular.groupby('nome')['roubo_celular']
    .sum().reset_index().sort_values(by='roubo_celular', ascending=False)
)
df_roubo_celular_agg

                                nome  roubo_celular
51         059ª DP - Duque de Caxias          12319
56      064ª DP - São João de Meriti           9414
30                   034ª DP - Bangu           8771
25               029ª DP - Madureira           7814
29                033ª DP - Realengo           7175
..                               ...            ...
93               111ª DP - Sumidouro              2
128  155ª DP - São Sebastião do Alto              1
125            152ª DP - Duas Barras              1
130      157ª DP - Trajano de Moraes              1
76          092ª DP - Rio das Flores              0

[138 rows x 2 columns]

In [21]:
roubo_celular_array = np.array(df_roubo_celular_agg['roubo_celular'])

media = np.mean(roubo_celular_array)
mediana = np.median(roubo_celular_array)
desvio = np.std(roubo_transeunte_array)

q1 = np.percentile(roubo_celular_array, 25)
q3 = np.percentile(roubo_celular_array, 75)
iqr = q3 - q1
#outliers - preparação
limite_inferior = q1 - 1.5*iqr
limite_superior = q3 + 1.5*iqr

In [22]:

print(f'Média: {media:.2f}')
print(f'Mediana: {mediana:.2f}')
print(f'Desvio padrão: {desvio:.2f}')
print(f'Q1: {q1:.2f}')
print(f'Q2/Mediana: {mediana:.2f}')
print(f'Q3: {q3:.2f}')
print(f'IQR: {iqr:.2f}')
print(f'Limite Inferior: {limite_inferior}')
print(f'Limite Superior: {limite_superior}')

Média: 2011.96
Mediana: 715.00
Desvio padrão: 10972.33
Q1: 43.25
Q2/Mediana: 715.00
Q3: 3746.50
IQR: 3703.25
Limite Inferior: -5511.625
Limite Superior: 9301.375